#!/usr/bin/env ruby


checks = %w{
  debugger
  Rails.logger
  logger
  puts
  save_and_open_page
  console.log
}

errors = []

files_changed = `git diff --name-only HEAD`
files_changed.each_line do |filename|
  filename.chomp!
  puts "Checking #{filename}: "
  changes = `git diff -U0 HEAD -- #{filename}`
  checks.each do |check|
    result = changes.split(/\n/).grep(/^\+.*\b#{check}/)
    unless result.empty?
      errors << {:name => check, :file => filename, :matches => result}
    end
  end
end

unless errors.empty?
  errors.each do |error|
    puts "'#{error[:name]}' found in file: #{error[:file]}"
    error[:matches].each {|m| puts "  -> #{m}" }
  end
  puts "COMMIT REJECTED. Please remove them before commiting OR use --no-verify"
  exit 1
end
